trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Set your ACR name
  acrName: 'ecommerceregistry1'
  imageName: 'user-service'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(acrName).azurecr.io/$(imageName)'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'ecommerceregistry1'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - script: |
        pwd
        ls -R
      displayName: 'Show working directory and files'

    - script: kubectl apply -f user-service/deployment.yaml --record
      displayName: 'Deploy to AKS'
