apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ecommerceregistry1.azurecr.io/order-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service"
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-sp-credentials
              key: client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-sp-credentials
              key: client-secret
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-sp-credentials
              key: tenant-id
      imagePullSecrets:
      - name: acr-secret1
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
